### ISSUE TITLE
About the usage of serverhub-cli 

### ISSUE THREAD

**Issue by maoyuyang** [ServerHubOrg/serverhub-mvc#1]
I think the usage of serverhub-cli is not very convenient 

the usage in README.md
```
npm i -g serverhub-cli
cd path/to/you/workspace/
npm init #ignore if you already done this
npm i --save serverhub-mvc
mkdir server && serverhub-cli init server -d #be sure to keep your files before add -h option to init command.
```

It's a little bit complicated ,  it could be modified like this
```
npm i -g serverhub-cli
cd path/to/you/workspace/
serverhub-cli init [projectName]
```

we should split the template into a new project rather than make some directory or files in index.js . In this way, we just need to download the template and replace the name . it can be decoupled .

Can I do this job ? :)

**Comment by maoyuyang** [comment]
不知道语法写的有没有问题。。练练英语~

**Comment by DevChache** [comment]
Thank you very much! I do agree it is a little complicated right now. And I think it would be great if you can modify and creat a pull request. Then we can make this tool better. Thanks again!

**Comment by DevChache** [comment]
Thanks @maoyuyang , the issue is fixed. Close issue now.
