### ISSUE TITLE
Document site migration

### ISSUE THREAD

**Issue by donley828** [ServerHubOrg/serverhub-mvc#5]
### Thinking
I think the document sites are important part of open source project.I spent a few hours to read serverhub's doc. I think it will be better if you make a little change.
### Example
Here is a [live-demo](http://donglei.site/vp-demo/) for this issue.This static site based on VuePress that is a static html generator.It has the following advantages：
- The sidebar has a clear index of the article section
- Greater syntax hignlight
- Good support for pictures and other elements
- Better management of the draft document
·······
### Usage
```bash
yarn global add vuepress # 或者：npm install -g vuepress
# create md
echo "# Hello VuePress!" > README.md
# write
vuepress dev .
# build
vuepress build .
```
For more information about this tool, [view on this](https://vuepress.vuejs.org/guide/)
### Final 
So, I'm glad to migrate this doc and maintain it if needed. lol...

**PLEASE point it if it have any mistakes in this paragraph**

**Comment by DevChache** [comment]
Good point! And thanks!

In fact, I think the current version of document site is not good at all. 

- For maintainance, I have to use many HTML mark-ups and many CSS rules for both Chinese and English versions. It is a huge work and really distracts my attention.
- For user experience, the current one is not good at all. Totally bad experience for document referring and tutorials sharing.

So I do agree there is a lot of things that can be improved on the doc site.

Maybe in next two weeks, I will spend some time working on VuePress. If it is available for our doc site, I will comment in this thread and invite you to join in the migration stuff as a member of this org. (The final result will be sent through serverhub.contact@gmail.com).

Many thanks! Have a nice day!

**Comment by DevChache** [comment]
Hi donley828, we've sent you an invitation through serverhub.contact@gmail.com, waiting for your confirmation!

And at the meantime, this issue will be closed, thanks for your support!
